import { createFileRoute } from "@tanstack/react-router";
import Artifacts from "@/pages/Artifacts";

export const Route = createFileRoute("/_app/artifacts")({
  head: () => ({
    meta: [
      { title: "Artifacts | Aether Platform" },
      { name: "description", content: "Files, documents and outputs generated by your agents." },
      { property: "og:title", content: "Artifacts | Aether Platform" },
      { property: "og:description", content: "Files, documents and outputs generated by your agents." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Artifacts,
});
